import localFont from "next/font/local";
import "./globals.css";
import Navigation from "./components/navigation/navigation";
import {
  Rubik_Wet_Paint,
  Zen_Tokyo_Zoo,
  Caveat,
  Inter,
} from "next/font/google";

export const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
});

export const rubik = Rubik_Wet_Paint({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-rubik-wet-paint",
});

export const zenTokyoZoo = Zen_Tokyo_Zoo({
  subsets: ["latin"],
  weight: ["400"],
});

export const caveat = Caveat({
  subsets: ["latin"],
  weight: ["500", "400"],
  variable: "--font-caveat",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html className={`w-dvw h-dvh flex flex-col overflow-hidden `} lang="en">
      <body className={`w-full h-full flex flex-col`}>
        <div className={`flex-grow z-10`}>{children}</div>
        <Navigation />
      </body>
    </html>
  );
}
