import localFont from "next/font/local";
import "./globals.css";
import Navigation from "./components/navigation/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={`w-full h-full flex flex-col overflow-hidden `} lang="en">
      <body className={`w-full h-full flex flex-col`}>
        <div className={`flex-grow z-10`}>{children}</div>
        <Navigation />
      </body>
    </html>
  );
}
